// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArbavgqFuy_CJtJu6FKrTVdDz9ys-jQ28',
    appId: '1:612930631250:web:693ba42bd49041aee1918b',
    messagingSenderId: '612930631250',
    projectId: 'vehicle-tracking-system-5d09e',
    authDomain: 'vehicle-tracking-system-5d09e.firebaseapp.com',
    databaseURL: 'https://vehicle-tracking-system-5d09e-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-system-5d09e.appspot.com',
    measurementId: 'G-PQCD30HEDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lS1BdqXSL12yYaa-3tYzCoa86Xrm-Sc',
    appId: '1:612930631250:android:71764b75e6a46cebe1918b',
    messagingSenderId: '612930631250',
    projectId: 'vehicle-tracking-system-5d09e',
    databaseURL: 'https://vehicle-tracking-system-5d09e-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-system-5d09e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZvyXlKdfPyEf3F8-UV8sOXAHrxx6-J0',
    appId: '1:612930631250:ios:2d999070e66b48a9e1918b',
    messagingSenderId: '612930631250',
    projectId: 'vehicle-tracking-system-5d09e',
    databaseURL: 'https://vehicle-tracking-system-5d09e-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-system-5d09e.appspot.com',
    iosBundleId: 'com.example.vehicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZvyXlKdfPyEf3F8-UV8sOXAHrxx6-J0',
    appId: '1:612930631250:ios:342268007ba7ac82e1918b',
    messagingSenderId: '612930631250',
    projectId: 'vehicle-tracking-system-5d09e',
    databaseURL: 'https://vehicle-tracking-system-5d09e-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-system-5d09e.appspot.com',
    iosBundleId: 'com.example.vehicle.RunnerTests',
  );
}
