/// Environment configuration for the app.
///
/// Firebase options are handled by [firebase_options.dart] (generated by FlutterFire CLI).
/// This file handles any additional environment-specific configuration.
///
/// To regenerate Firebase config:
/// ```sh
/// flutterfire configure
/// ```
class EnvConfig {
  EnvConfig._();

  /// Whether to use Firebase emulators for local development.
  static const bool useEmulators = bool.fromEnvironment(
    'USE_EMULATORS',
    defaultValue: false,
  );

  /// Firebase emulator host (for local development).
  static const String emulatorHost = String.fromEnvironment(
    'EMULATOR_HOST',
    defaultValue: '10.0.2.2', // Android emulator localhost
  );

  /// Firebase Auth emulator port.
  static const int authEmulatorPort = int.fromEnvironment(
    'AUTH_EMULATOR_PORT',
    defaultValue: 9099,
  );

  /// Firebase RTDB emulator port.
  static const int databaseEmulatorPort = int.fromEnvironment(
    'DATABASE_EMULATOR_PORT',
    defaultValue: 9000,
  );
}
